### ISSUE TITLE
Create a heroku account for the 919mexico backend

### ISSUE THREAD

**Issue by NelsonSuperSonic** [SuperSonicDesignINC/919mexico-gatsbyjs-mysql-strapi#1]
Hi @kageyamatamio , could you create a heroku account for 919 mexico ... it is necessary that the credit card is enabled.

**Comment by kageyamatamio** [comment]
OK. I wil do it today.

**Comment by NelsonSuperSonic** [comment]
Hi @kageyamatamio sorry, Mr. DJ informed me that we already have an account for 919mexico, we will use it.

**Comment by kageyamatamio** [comment]
ok ! Thanks
